package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"golang.org/x/oauth2"
)

// PythonToken matches the structure generated by google-auth in Python
type PythonToken struct {
	Token        string   `json:"token"`
	RefreshToken string   `json:"refresh_token"`
	TokenURI     string   `json:"token_uri"`
	ClientID     string   `json:"client_id"`
	ClientSecret string   `json:"client_secret"`
	Scopes       []string `json:"scopes"`
	Expiry       string   `json:"expiry"`
}

func getGmailCredentials() (*oauth2.Token, error) {
	tokenPath := os.Getenv("GMAIL_TOKEN_PATH")
	if tokenPath == "" {
		tokenPath = filepath.Join("..", "token.json")
	}

	if _, err := os.Stat(tokenPath); os.IsNotExist(err) {
		tokenPath = "token.json" // try current directory
	}

	credsData, err := os.ReadFile(tokenPath)
	if err != nil {
		return nil, fmt.Errorf("could not read token.json at %s: %w", tokenPath, err)
	}
	_ = os.Chmod(tokenPath, 0o600)

	var pt PythonToken
	if err := json.Unmarshal(credsData, &pt); err != nil {
		return nil, fmt.Errorf("could not parse token.json: %w", err)
	}

	expiryTime, err := time.Parse(time.RFC3339Nano, pt.Expiry)
	if err != nil {
		// Try without Nano if it fails
		expiryTime, err = time.Parse(time.RFC3339, pt.Expiry)
		if err != nil {
			return nil, fmt.Errorf("could not parse expiry time %s: %w", pt.Expiry, err)
		}
	}

	token := &oauth2.Token{
		AccessToken:  pt.Token,
		TokenType:    "Bearer",
		RefreshToken: pt.RefreshToken,
		Expiry:       expiryTime,
	}

	// Create oauth config to auto-refresh if needed
	conf := &oauth2.Config{
		ClientID:     pt.ClientID,
		ClientSecret: pt.ClientSecret,
		Endpoint: oauth2.Endpoint{
			TokenURL: pt.TokenURI,
		},
		Scopes: pt.Scopes,
	}

	tokenSource := conf.TokenSource(context.Background(), token)
	newToken, err := tokenSource.Token()
	if err != nil {
		return nil, fmt.Errorf("could not refresh token: %w", err)
	}

	// If the token was refreshed, save it back
	if newToken.AccessToken != pt.Token {
		pt.Token = newToken.AccessToken
		pt.RefreshToken = newToken.RefreshToken
		pt.Expiry = newToken.Expiry.Format(time.RFC3339Nano)

		updatedData, err := json.Marshal(pt)
		if err == nil {
			_ = os.WriteFile(tokenPath, updatedData, 0o600)
		}
	}

	return newToken, nil
}
